#+TITLE: Некоторая информация о летнем лагере
#+OPTIONS: toc:nil num:nil email:t creator:t
#+EMAIL: shender.i <AT> gmail <DOT> com
#+STYLE: <link rel="stylesheet" type="text/css" href="css/style.css" />

Здесь собрана полезная информация, которая не меняется от лагеря к
лагерю.


* Исторические сведения. 

Им посвящена отдельная [[file:history.org][страница]]. 

* Ежедневные задачи.

Ежедневные задачи вывешиваются каждый день. Комплект ежедневных задач,
не меняющийся уже много лет, существует для [[file:~/dc/fizega/camp_common/2-a-day/2-a-day-07.pdf][самых маленьких]], [[file:~/dc/fizega/camp_common/2-a-day/2-a-day-08.pdf][8 класса]],
[[file:~/dc/fizega/camp_common/2-a-day/2-a-day-09.pdf][9 класса]], [[file:~/dc/fizega/camp_common/2-a-day/2-a-day-10.pdf][10 класса]] и [[file:~/dc/fizega/camp_common/2-a-day/2-a-day-11.pdf][11 класса]]. 

* Эксперимент.

В данный момент доступны сводные таблицы с кратким описанием почти
всех экспериментов, проведённых в лагере в [[file:exp2010.org][2010]] и [[file:exp2011.org][2011]] году (если бы
отдельные товарищи в лице Феди, Феди и Антона прислали материалы по
своим занятиям, то слово «почти» можно было бы убрать).

Кроме того, проводящим эксперимент рекомендуется книжка Варламова,
Зильбермана и Зинковского «Экспериментальные задачи на уроках физики и
физических олимпиадах», М., 2009. Скачать её можно [[https://www.dropbox.com/s/rw7zjoigmwqwz0o/varlamov_zilberman_exp.pdf][тут]]. 

* Физические бои.

Физические бои устраиваются на две команды ([[file:battle/rules_dual.pdf][правила]]) или на три
команды ([[file:battle/rules_triple.pdf][правила]]).

* Задачи. 

Несколько книжек с задачами могут быть найдены [[https://www.dropbox.com/sh/zeqwh7ufkxatd1e/esfadNz7rZ][здесь]]. Осторожно,
некоторые книжки весят по 10 Мб и более. 

Кроме того, не следует забывать [[http://physolymp.spb.ru/index.php?option%3Dcom_content&task%3Dview&id%3D335&Itemid%3D55][архив с задачами]] на нашем олимпиадном
сайте. 

Для удобного подбора и поиска задач по ключевым словам я написал
небольшой скрипт (работает только в =Linux=), описание которого можно
найти [[https://github.com/shender/pdb][тут]] (zip–файл со скриптом и базой задач — [[https://github.com/shender/pdb/zipball/master][здесь]]). Задачи собраны
из разных источников. Пока их не так много (около 150), но количество
всё время увеличивается. Также приветствуется помощь по добавлению
задач в базу.
